---
- name: Create users
  ansible.builtin.user:
    name: "{{ item.username }}"
    shell: "{{ item.shell }}"
    groups: root
  with_items:
    - "{{ users_info }}"

- name: Change "users" password
  ansible.builtin.user:
    name: "{{ item.username }}"
    update_password: always
    password: "{{ newpassword | password_hash('sha512') }}"
  with_items:
    - "{{ users_info }}"
  no_log: true

- name: Add ssh key for users
  tags: always
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.pub_key }}"
  with_items:
    - "{{ users_info }}"

- name: Add sudoers file for ansible # noqa: no-tabs
  ansible.builtin.copy:
    content: '{{ item.username }} ALL=(ALL)	NOPASSWD: ALL'
    dest: /etc/sudoers.d/{{ item.username }}
    owner: root
    group: root
    mode: '0440'
  with_items:
    - "{{ users_info }}"

- name: Add ssh config file
  ansible.builtin.copy:
    src: templates/sshd_config
    dest: /etc/ssh/ssdh_config
    mode: '0600'
    owner: root
    group: root
  notify: Reboot_sshd # noqa: args[module]
