## task list for common_tasks role

---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Set selinux policy # noqa: args[module]
  ansible.posix.selinux:
    policy: targeted
    state: "{{ selinux_state }}"
  when: ( 'localhost' not in inventory_hostname ) and (ansible_os_family in ['RedHat', 'Rocky'])

- name: Upgrade all packages
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Install packages # noqa: args[module] loop-var-prefix[missing]
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ custom_packages_installed }}"
